### ISSUE TITLE
Change port and new actions

### ISSUE THREAD

**Issue by Tanis74** [bitfocus/companion-module-noismada-octopusshowcontrol#10]
Hi. Please add the ability to change the connection port when adding an instance. There are also not enough actions to launch a shell сommand script and open a presentation file.

Open file	
`<TYPE>P</TYPE><Value1>OF</Value1><Value2>File_Name.pptx</Value2>%0D`

Shell Command
`<TYPE>S</TYPE><Value1>Command*</Value1><Value2>Password**</Value2>%0D`
	*Command to be replaced w/Command Script
	**Password to be replaced w/Password for Machine

**Comment by JeffreyDavidsz** [comment]
The port can be changed in the settings already (according to the code), which version of Companion are you using?

**Comment by Tanis74** [comment]
2.2.0 (2.2.0+3998-ccea40c7)

![image](https://user-images.githubusercontent.com/5111569/164442611-4b1361b5-aefa-451f-9527-b5b61c4bbf3a.png)
