### ISSUE TITLE
Define all keys for Octupus Listener (free)...

### ISSUE THREAD

**Issue by rofrance19** [bitfocus/companion-module-noismada-octopusshowcontrol#11]
Trying to use Octopus Listener (free) to control my DAW (Cakewalk).   I need to send key sequences other than the ones which are defined.      Actions.js includes some keys, but not all.      1) is the list constrained for any reason, such a maybe a list limit?   2) is there any reason we cannot have all the keys defined?    I could fork and contribute them; would be my first contribution, which I'm happy to do.

**Comment by JeffreyDavidsz** [comment]
It's the reason why I've created vicreo-listener. If you use a single keystroke you can use the basic (free) version (download: https://www.vicreo-listener.com). And use it with vicreo-hotkey module in Companion. You could also contribute to the module but no guarantee that Octopus will accept them.

**Comment by rofrance19** [comment]
The keystrokes I need are  CTRL-End, CTRL-A, ALT-R, and then R, and after recording is over, spacebar.    I'll look at vicre-listener now.

**Comment by rofrance19** [comment]
I have it working now...   very cool... Thanks MUCH!
