### ISSUE TITLE
New Octopus Listener version 1.0.3

### ISSUE THREAD

**Issue by tmurfin** [bitfocus/companion-module-noismada-octopusshowcontrol#9]
This module is not working with the newest version of listener v1.0.3. The protocols for this version are different with the rewrite to 64bit paid version of octopus.

**Comment by JeffreyDavidsz** [comment]
It's a know thing, can you get an API? Then I can make a module for it. We have adjusted the octopus app module already

**Comment by tmurfin** [comment]
Ya, I will get it too you soon. I will have to make something, there isn’t any documentation for listeners protocol.

**Comment by tmurfin** [comment]
Command Type		Command


Keynote:

	Play				<TYPE>K</TYPE><Value1>P</Value1>%0D
	Stop				<TYPE>K</TYPE><Value1>S</Value1>%0D
	Next slide			<TYPE>K</TYPE><Value1>N</Value1>%0D
	Back Slide			<TYPE>K</TYPE><Value1>B</Value1>%0D

	Goto slide			<TYPE>K</TYPE><Value1>G</Value1><Value2>Slide_Number*</Value2>%0D

		*to be replaced w/Slide Number

	Open				<TYPE>K</TYPE><Value1>O</Value1>%0D

	Open file			<TYPE>K</TYPE><Value1>OF</Value1><Value2>File_Name.Key</Value2>%0D

	Quit				<TYPE>K</TYPE><Value1>Q</Value1>%0D





Powerpoint:

	Play				<TYPE>P</TYPE><Value1>P</Value1>%0D
	Stop				<TYPE>P</TYPE><Value1>S</Value1>%0D
	Next slide			<TYPE>P</TYPE><Value1>N</Value1>%0D
	Back Slide			<TYPE>P</TYPE><Value1>B</Value1>%0D

	Goto slide			<TYPE>P</TYPE><Value1>G</Value1><Value2>Slide_Number*</Value2>%0D

		*to be replaced w/Slide Number

	Open				<TYPE>P</TYPE><Value1>O</Value1>%0D

	Open file			<TYPE>P</TYPE><Value1>OF</Value1><Value2>File_Name.pptx</Value2>%0D

	Quit				<TYPE>P</TYPE><Value1>Q</Value1>%0D




Keystroke:

	Keystroke			<TYPE>KS</TYPE><Value1>Keystroke*</Value1>%0D
	
		*Keystroke to be replaced w/Input Value

Keystroke String:

	Keystroke String		<TYPE>KSS</TYPE><Value1>String*</Value1>%0D

		*String to be replaced w/Input Value

Shell Command:

	Shell				<TYPE>S</TYPE><Value1>Command*</Value1><Value2>Password**</Value2>%0D

		*Command to be replaced w/Command Script
		**Password to be replaced w/Password for Machine

**Comment by JeffreyDavidsz** [comment]
@tmurfin Thanks for that! What I'm missing is a key combo like alt tab or command tab
`<TYPE>KS</TYPE><Value1>Option/Alt</Value1><Value2>Tab</Value2>`
does not work (probably because the / between Option/Alt), do you know if that modifier has been changed?

**Comment by JeffreyDavidsz** [comment]
Todo: [Shell] [Keystroke String] [Keystroke (multiple characters?)] [open file]

**Comment by tmurfin** [comment]
I will ask about that, but I'm not sure at the moment. I will look into it later tonight.

**Comment by tmurfin** [comment]
Key combos would be done like this. Option is the equivalent to alt on pc so it should work without having it say it, at least in the physical code that is sent.

<TYPE>KS</TYPE><Value1>Option+Tab</Value1>%0D

**Comment by tmurfin** [comment]
`<TYPE>KS</TYPE><Value1>Option+Tab</Value1>%0D`

Sorry, it didn't keep my format, here's the full syntax line.

**Comment by brucedk** [comment]
Is this merge? i'm trying to work with it with companion 2.4.1 and it connects, but do not send anything ( I'm using free version)

**Comment by JeffreyDavidsz** [comment]
I would say so, but I switched my effort to VICREO listener. Because I can alter that program myself. There is a free version also for that

**Comment by tmurfin** [comment]
The paid version works great (listener 1.0.3). I haven’t used the free version (listener 1.0.2) but you don’t actually pay for the paid version of octopus listener, it’s free, just octopus itself is paid.

**Comment by seanmcnally98** [comment]
Silly question here, but how did you find these commands for keynote?  I can't seem to find proper documentation anywhere.  Did you just use wireshark to figure them out?

Also, what protocol does Octopus listener use, is it TCP?
